name: Format Code and Create PR

on:
  push:
    branches: [ "main" ]

jobs:
  format-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Format code
        run: |
          sudo apt-get install -y clang-format
          clang-format -i **/*.cpp **/*.h

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply code formatting"
          title: "Code formatting proposal"
          body: "This PR applies clang-format to the codebase."
