name: Format Code and Create PR

on:
  push:
    branches: [ "main" ]

jobs:
  format-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3
      # - uses: RafikFarhad/clang-format-github-action@v3
      #   with:
      #     sources: "include/**/*.h,include/**/*.hpp,src/**/*.c,src/**/*.cpp"

      - name: Test dubious owner thing
        run: |
          git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3
      - uses: AutoModality/action-ros-clang-format@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Format code
      #   run: |
      #     sudo apt-get install -y clang-format
      #     clang-format -i include/**/*.h,include/**/*.hpp,src/**/*.c,src/**/*.cpp

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Apply code formatting"
          title: "Code formatting proposal"
          body: "This PR applies clang-format to the codebase."
