name: Code Formatter
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  clang-format:
      runs-on: ubuntu-latest
      steps:
      # - name: Adds GitHub workspace as safe directory
      #   run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Set up JGit
        run: |
          wget -O jgit.jar https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/5.13.0.202109080827-r/org.eclipse.jgit-5.13.0.202109080827-r.jar
          alias git="java -jar jgit.jar"      
      # - name: Set up Git
      #   run: |
      #     sudo add-apt-repository -y ppa:git-core/ppa
      #     sudo apt-get update
      #     sudo apt-get install -y git
      - name: Adds GitHub workspace as safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
        # run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3.1.0
        with:
          set-safe-directory: '*'
      - uses: AutoModality/action-ros-clang-format@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FORMATTER }}